# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(537, 318)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/a8abd29a96d4222680540c6bd2e3595e.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.barra_progresso = QtWidgets.QProgressBar(self.centralwidget)
        self.barra_progresso.setGeometry(QtCore.QRect(270, 294, 247, 10))
        self.barra_progresso.setStyleSheet("QProgressBar {\n"
"    background: rgba(255, 255, 255, 180);\n"
"    border-style: none;\n"
"    border-radius: 5px;\n"
"    color: rgba(200, 200, 200, 0); /* Esta cor está transparente, então o texto não aparecerá */\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border-radius: 5px;\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(136, 0, 0, 255), stop:1 rgba(255, 85, 0, 255)) /* missing value here, assuming you will put one */\n"
"}")
        self.barra_progresso.setProperty("value", 0)
        self.barra_progresso.setAlignment(QtCore.Qt.AlignCenter)
        self.barra_progresso.setTextVisible(False)
        self.barra_progresso.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.barra_progresso.setObjectName("barra_progresso")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(12, 48, 217, 223))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/cummins.ico"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.campoStats = QtWidgets.QTextEdit(self.centralwidget)
        self.campoStats.setEnabled(False)
        self.campoStats.setGeometry(QtCore.QRect(264, 48, 247, 229))
        self.campoStats.setStyleSheet("background-color: transparent;\n"
"border: none")
        self.campoStats.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.campoStats.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.campoStats.setObjectName("campoStats")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-1, -5, 253, 331))
        self.widget.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 9, 1, 255), stop:1 rgba(255, 100, 0, 255))")
        self.widget.setObjectName("widget")
        self.widget.raise_()
        self.barra_progresso.raise_()
        self.campoStats.raise_()
        self.label.raise_()
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Preparing environment..."))
import icons
