# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_registerWindow(object):
    def setupUi(self, registerWindow):
        registerWindow.setObjectName("registerWindow")
        registerWindow.resize(789, 389)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/a8abd29a96d4222680540c6bd2e3595e.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        registerWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(registerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(24, 192, 150, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("background-color:transparent;\n"
"color:rgb(130,130,130)")
        self.label_30.setObjectName("label_30")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(516, 42, 73, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("background-color:transparent;\n"
"color:rgb(130,130,130)")
        self.label_45.setObjectName("label_45")
        self.new_category = QtWidgets.QComboBox(self.centralwidget)
        self.new_category.setGeometry(QtCore.QRect(24, 138, 607, 30))
        self.new_category.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.new_category.setFont(font)
        self.new_category.setStyleSheet("QComboBox {\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(90, 54, 247);\n"
"    border-radius: 0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QComboBox:disabled, QComboBox:!focus {\n"
"    border-bottom: 1px solid rgb(120, 120, 120);\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 0;\n"
"}")
        self.new_category.setObjectName("new_category")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(24, 36, 79, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("background-color:transparent;\n"
"color:rgb(130,130,130)")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(24, 114, 73, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("background-color:transparent;\n"
"color:rgb(130,130,130)")
        self.label_28.setObjectName("label_28")
        self.supplier_register = QtWidgets.QLineEdit(self.centralwidget)
        self.supplier_register.setEnabled(True)
        self.supplier_register.setGeometry(QtCore.QRect(516, 60, 247, 30))
        self.supplier_register.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.supplier_register.setFont(font)
        self.supplier_register.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(90, 54, 247);\n"
"    border-radius: 0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLineEdit:disabled, QLineEdit:!focus {\n"
"    border-bottom: 1px solid rgb(120, 120, 120);\n"
"}")
        self.supplier_register.setText("")
        self.supplier_register.setReadOnly(False)
        self.supplier_register.setObjectName("supplier_register")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(540, 192, 150, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("background-color:transparent;\n"
"color:rgb(130,130,130)")
        self.label_29.setObjectName("label_29")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(648, 120, 73, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("background-color:transparent;\n"
"color:rgb(130,130,130)")
        self.label_41.setObjectName("label_41")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(282, 192, 150, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("background-color:transparent;\n"
"color:rgb(130,130,130)")
        self.label_31.setObjectName("label_31")
        self.btn_save_new_supplier = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_new_supplier.setGeometry(QtCore.QRect(642, 348, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_save_new_supplier.setFont(font)
        self.btn_save_new_supplier.setObjectName("btn_save_new_supplier")
        self.bu_register_new = QtWidgets.QComboBox(self.centralwidget)
        self.bu_register_new.setGeometry(QtCore.QRect(648, 138, 115, 30))
        self.bu_register_new.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.bu_register_new.setFont(font)
        self.bu_register_new.setStyleSheet("QComboBox {\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(90, 54, 247);\n"
"    border-radius: 0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QComboBox:disabled, QComboBox:!focus {\n"
"    border-bottom: 1px solid rgb(120, 120, 120);\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 0;\n"
"}")
        self.bu_register_new.setObjectName("bu_register_new")
        self.vendor_register_new = QtWidgets.QLineEdit(self.centralwidget)
        self.vendor_register_new.setGeometry(QtCore.QRect(24, 60, 469, 30))
        self.vendor_register_new.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.vendor_register_new.setFont(font)
        self.vendor_register_new.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(90, 54, 247);\n"
"    border-radius: 0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLineEdit:disabled, QLineEdit:!focus {\n"
"    border-bottom: 1px solid rgb(120, 120, 120);\n"
"}")
        self.vendor_register_new.setObjectName("vendor_register_new")
        self.region_register_new = QtWidgets.QLineEdit(self.centralwidget)
        self.region_register_new.setEnabled(True)
        self.region_register_new.setGeometry(QtCore.QRect(390, 294, 145, 30))
        self.region_register_new.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.region_register_new.setFont(font)
        self.region_register_new.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(90, 54, 247);\n"
"    border-radius: 0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLineEdit:disabled, QLineEdit:!focus {\n"
"    border-bottom: 1px solid rgb(120, 120, 120);\n"
"}")
        self.region_register_new.setText("")
        self.region_register_new.setReadOnly(False)
        self.region_register_new.setObjectName("region_register_new")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(24, 270, 150, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("background-color:transparent;\n"
"color:rgb(130,130,130)")
        self.label_49.setObjectName("label_49")
        self.label_51 = QtWidgets.QLabel(self.centralwidget)
        self.label_51.setGeometry(QtCore.QRect(390, 270, 150, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("background-color:transparent;\n"
"color:rgb(130,130,130)")
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.centralwidget)
        self.label_52.setGeometry(QtCore.QRect(558, 270, 150, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("background-color:transparent;\n"
"color:rgb(130,130,130)")
        self.label_52.setObjectName("label_52")
        self.label_50 = QtWidgets.QLabel(self.centralwidget)
        self.label_50.setGeometry(QtCore.QRect(204, 270, 150, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("background-color:transparent;\n"
"color:rgb(130,130,130)")
        self.label_50.setObjectName("label_50")
        self.document_register_new = QtWidgets.QLineEdit(self.centralwidget)
        self.document_register_new.setEnabled(True)
        self.document_register_new.setGeometry(QtCore.QRect(558, 294, 205, 30))
        self.document_register_new.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.document_register_new.setFont(font)
        self.document_register_new.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(90, 54, 247);\n"
"    border-radius: 0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLineEdit:disabled, QLineEdit:!focus {\n"
"    border-bottom: 1px solid rgb(120, 120, 120);\n"
"}")
        self.document_register_new.setText("")
        self.document_register_new.setReadOnly(False)
        self.document_register_new.setObjectName("document_register_new")
        self.ssid_register_new = QtWidgets.QLineEdit(self.centralwidget)
        self.ssid_register_new.setEnabled(True)
        self.ssid_register_new.setGeometry(QtCore.QRect(24, 294, 157, 30))
        self.ssid_register_new.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ssid_register_new.setFont(font)
        self.ssid_register_new.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(90, 54, 247);\n"
"    border-radius: 0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLineEdit:disabled, QLineEdit:!focus {\n"
"    border-bottom: 1px solid rgb(120, 120, 120);\n"
"}")
        self.ssid_register_new.setText("")
        self.ssid_register_new.setReadOnly(False)
        self.ssid_register_new.setObjectName("ssid_register_new")
        self.country_register_new = QtWidgets.QLineEdit(self.centralwidget)
        self.country_register_new.setEnabled(True)
        self.country_register_new.setGeometry(QtCore.QRect(204, 294, 163, 30))
        self.country_register_new.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.country_register_new.setFont(font)
        self.country_register_new.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(90, 54, 247);\n"
"    border-radius: 0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLineEdit:disabled, QLineEdit:!focus {\n"
"    border-bottom: 1px solid rgb(120, 120, 120);\n"
"}")
        self.country_register_new.setText("")
        self.country_register_new.setReadOnly(False)
        self.country_register_new.setObjectName("country_register_new")
        self.sqie_register_new = QtWidgets.QComboBox(self.centralwidget)
        self.sqie_register_new.setGeometry(QtCore.QRect(24, 216, 235, 30))
        self.sqie_register_new.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sqie_register_new.setFont(font)
        self.sqie_register_new.setStyleSheet("QComboBox {\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(90, 54, 247);\n"
"    border-radius: 0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QComboBox:disabled, QComboBox:!focus {\n"
"    border-bottom: 1px solid rgb(120, 120, 120);\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 0;\n"
"}")
        self.sqie_register_new.setObjectName("sqie_register_new")
        self.sourcing_register_new = QtWidgets.QComboBox(self.centralwidget)
        self.sourcing_register_new.setGeometry(QtCore.QRect(282, 216, 241, 30))
        self.sourcing_register_new.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sourcing_register_new.setFont(font)
        self.sourcing_register_new.setStyleSheet("QComboBox {\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(90, 54, 247);\n"
"    border-radius: 0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QComboBox:disabled, QComboBox:!focus {\n"
"    border-bottom: 1px solid rgb(120, 120, 120);\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 0;\n"
"}")
        self.sourcing_register_new.setObjectName("sourcing_register_new")
        self.continuity_register_new = QtWidgets.QComboBox(self.centralwidget)
        self.continuity_register_new.setGeometry(QtCore.QRect(540, 216, 223, 30))
        self.continuity_register_new.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.continuity_register_new.setFont(font)
        self.continuity_register_new.setStyleSheet("QComboBox {\n"
"    border: none;\n"
"    border-bottom: 1px solid rgb(90, 54, 247);\n"
"    border-radius: 0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QComboBox:disabled, QComboBox:!focus {\n"
"    border-bottom: 1px solid rgb(120, 120, 120);\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 0;\n"
"}")
        self.continuity_register_new.setObjectName("continuity_register_new")
        registerWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(registerWindow)
        QtCore.QMetaObject.connectSlotsByName(registerWindow)
        registerWindow.setTabOrder(self.vendor_register_new, self.supplier_register)
        registerWindow.setTabOrder(self.supplier_register, self.new_category)
        registerWindow.setTabOrder(self.new_category, self.bu_register_new)
        registerWindow.setTabOrder(self.bu_register_new, self.sqie_register_new)
        registerWindow.setTabOrder(self.sqie_register_new, self.sourcing_register_new)
        registerWindow.setTabOrder(self.sourcing_register_new, self.continuity_register_new)
        registerWindow.setTabOrder(self.continuity_register_new, self.ssid_register_new)
        registerWindow.setTabOrder(self.ssid_register_new, self.country_register_new)
        registerWindow.setTabOrder(self.country_register_new, self.region_register_new)
        registerWindow.setTabOrder(self.region_register_new, self.document_register_new)
        registerWindow.setTabOrder(self.document_register_new, self.btn_save_new_supplier)

    def retranslateUi(self, registerWindow):
        _translate = QtCore.QCoreApplication.translate
        registerWindow.setWindowTitle(_translate("registerWindow", "Register new Supplier"))
        self.label_30.setText(_translate("registerWindow", "SQIE"))
        self.label_45.setText(_translate("registerWindow", "Supplier"))
        self.label_27.setText(_translate("registerWindow", "Vendor"))
        self.label_28.setText(_translate("registerWindow", "Category"))
        self.label_29.setText(_translate("registerWindow", "Continuity"))
        self.label_41.setText(_translate("registerWindow", "BU"))
        self.label_31.setText(_translate("registerWindow", "Sourcing"))
        self.btn_save_new_supplier.setText(_translate("registerWindow", "Save supplier"))
        self.label_49.setText(_translate("registerWindow", "SSID"))
        self.label_51.setText(_translate("registerWindow", "Region"))
        self.label_52.setText(_translate("registerWindow", "Document"))
        self.label_50.setText(_translate("registerWindow", "Country"))
import icons


