# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectSupplier.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windowSelectSupplier(object):
    def setupUi(self, windowSelectSupplier):
        windowSelectSupplier.setObjectName("windowSelectSupplier")
        windowSelectSupplier.resize(704, 562)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/a8abd29a96d4222680540c6bd2e3595e.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        windowSelectSupplier.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(windowSelectSupplier)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_select_vendor = QtWidgets.QPushButton(self.centralwidget)
        self.btn_select_vendor.setGeometry(QtCore.QRect(588, 522, 100, 30))
        self.btn_select_vendor.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_select_vendor.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_select_vendor.setFont(font)
        self.btn_select_vendor.setObjectName("btn_select_vendor")
        self.table_select_supplier = QtWidgets.QTableWidget(self.centralwidget)
        self.table_select_supplier.setGeometry(QtCore.QRect(12, 12, 679, 499))
        self.table_select_supplier.setObjectName("table_select_supplier")
        self.table_select_supplier.setColumnCount(4)
        self.table_select_supplier.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_select_supplier.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_select_supplier.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_select_supplier.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_select_supplier.setHorizontalHeaderItem(3, item)
        self.table_select_supplier.horizontalHeader().setDefaultSectionSize(117)
        self.table_select_supplier.verticalHeader().setVisible(False)
        windowSelectSupplier.setCentralWidget(self.centralwidget)

        self.retranslateUi(windowSelectSupplier)
        QtCore.QMetaObject.connectSlotsByName(windowSelectSupplier)

    def retranslateUi(self, windowSelectSupplier):
        _translate = QtCore.QCoreApplication.translate
        windowSelectSupplier.setWindowTitle(_translate("windowSelectSupplier", "Select Supplier"))
        self.btn_select_vendor.setText(_translate("windowSelectSupplier", "Select"))
        item = self.table_select_supplier.horizontalHeaderItem(0)
        item.setText(_translate("windowSelectSupplier", "Id"))
        item = self.table_select_supplier.horizontalHeaderItem(1)
        item.setText(_translate("windowSelectSupplier", "Vendor"))
        item = self.table_select_supplier.horizontalHeaderItem(2)
        item.setText(_translate("windowSelectSupplier", "Supplier"))
        item = self.table_select_supplier.horizontalHeaderItem(3)
        item.setText(_translate("windowSelectSupplier", "BU"))
import icons


